---
- hosts: "{{ variable_host | default('alpha')}}"
  remote_user: continuum
  sudo: yes
  tasks:
     - name: Checking system disk space
       script: /path/to/diskcheck2.sh 
       register: result
     - name: printing result  	       
       debug: var=result.stdout_lines	
