---
- hosts: "{{ variable_host | default('alpha')}}"
  remote_user: continuum
  sudo: yes

  tasks:
    - name: install fail2ban
      command: apt-get install fail2ban

    - name: check fail2ban status
      service: name=fail2ban state=started enabled=yes


