---
- hosts: "{{ variable_host | default('alpha')}}"
  remote_user: continuum
  sudo: yes

  tasks:
   - name: starting ufw
     service: name=ufw state=started enabled=yes
     when: ansible_os_family == "Debian"
   - name: starting firewalld
     service: name=firewalld state=started enabled=yes
     when: ansible_os_family == "RedHat"	

