---
- hosts: "{{ variable_host | default('alpha') }}"
  remote_user: continuum
  sudo: yes

  tasks:
    - name: Creating Local Directory To Keep Files
      file: path=/tmp/ftp-{{ inventory_hostname }} state=directory mode=0755

    - name: Copying ftp files from Remote Server
      fetch: src=/path/to/ftp/files dest=/tmp/ftp-{{ inventory_hostname }} flat=yes
