---
- hosts: "{{ variable_host | default('alpha')}}"
  remote_user: continuum
  sudo: yes
  tasks:
     - name: finding .delete directories
       script: /path/to/finddirs.sh 
       register: result
     - name: printing result  	       
       debug: var=result.stdout_lines	
