---
- hosts: "{{ variable_host | default('alpha') }}"
  remote_user: continuum
  sudo: yes

  tasks:
    - name: Including variable file
      include_vars: vars/jobnames.yml

    - cron: name="mycron" hour="3" minute="0" user="root" job={{ item }}
      with_items: "{{ jobnames }}" 
        
